/**
 * Utility functions for exporting ROP chains to pwntools Python code.
 *
 * @module utils/exportPwntools
 */

import { StackItem } from '../types';
import { GADGETS } from '../data/gadgets';

/**
 * Looks up a gadget by its ID from the predefined GADGETS array.
 *
 * @param id - The gadget ID to search for.
 * @returns The matching Gadget object, or undefined if not found.
 */
const getGadgetById = (id: string) => GADGETS.find(g => g.id === id);

/**
 * Converts a stack of StackItems into a pwntools-compatible Python script.
 *
 * The generated script includes:
 * - pwntools imports and context setup (amd64, linux)
 * - ROP chain construction using `rop.raw()` calls
 * - Process launch and interactive mode
 *
 * @param stack - Array of StackItems representing the ROP chain.
 * @returns A string containing the complete Python pwntools script.
 *
 * @example
 * ```typescript
 * const items: StackItem[] = [
 *   { id: '1', type: 'gadget', value: '0x4005d7', gadgetId: 'gadget-pop-rax-ret', label: 'POP RAX; RET' },
 *   { id: '2', type: 'value', value: '0x3b', label: 'execve (59)' },
 *   { id: '3', type: 'gadget', value: '0x4005d3', gadgetId: 'gadget-pop-rdi-ret', label: 'POP RDI; RET' },
 *   { id: '4', type: 'value', value: '0x7fff', label: '/bin/sh' },
 *   { id: '5', type: 'gadget', value: '0x4005d9', gadgetId: 'gadget-syscall', label: 'SYSCALL' },
 * ];
 * const code = exportToPwntools(items);
 * // Returns Python script with rop.raw() calls for each item
 * ```
 */
export const exportToPwntools = (stack: StackItem[]): string => {
  const lines: string[] = [
    'from pwn import *',
    '',
    'context.arch = \'amd64\'',
    'context.os = \'linux\'',
    '',
    '# ROP Chain for binary exploitation',
    '# Generated by VStack - Visual ROP Chain Builder',
    '',
    'rop = ROP("./binary")',
    '',
  ];

  for (const item of stack) {
    if (item.type === 'gadget' && item.gadgetId) {
      const gadget = getGadgetById(item.gadgetId);
      if (gadget) {
        lines.push(`rop.raw(${item.value})  # ${gadget.instructions.join('; ')}`);
      }
    } else {
      lines.push(`rop.raw(${item.value})  # ${item.label || 'value'}`);
    }
  }

  lines.push('');
  lines.push('# Execute the chain');
  lines.push('p = process("./binary")');
  lines.push('rop.call(p)');
  lines.push('p.interactive()');

  return lines.join('\n');
};

/**
 * Copies text to the system clipboard using the Clipboard API.
 *
 * @param text - The text to copy to clipboard.
 * @returns `true` if the copy succeeded, `false` if it failed (e.g., no permission).
 *
 * @example
 * ```typescript
 * const success = await copyToClipboard('0x4005d3');
 * if (success) showCopiedFeedback();
 * ```
 */
export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
};
