/**
 * Utility functions for exporting ROP chains to pwntools Python code.
 *
 * @module utils/exportPwntools
 */

import { StackItem } from '../types';
import { GADGETS } from '../data/gadgets';

/**
 * Looks up a gadget by its ID from the predefined GADGETS array.
 *
 * @param id - The gadget ID to search for.
 * @returns The matching Gadget object, or undefined if not found.
 */
const getGadgetById = (id: string) => GADGETS.find(g => g.id === id);

/**
 * Converts a stack of StackItems into a runnable pwntools Python script.
 *
 * Template (validated vs CTF writeups):
 * - flat/p64 chain, padding offset placeholder, ELF/process, send + interactive
 * - 1:1 mapping from stackItems so VStack layout == payload layout
 *
 * @param stack - Array of StackItems representing the ROP chain.
 * @param offset - Padding length to RIP (default 40, e.g., 32 buf + 8 RBP).
 * @returns A string containing the complete Python pwntools script.
 *
 * @example
 * ```typescript
 * const items: StackItem[] = [
 *   { id: '1', type: 'gadget', value: '0x4005e5', gadgetId: 'gadget-pop-rax-ret', label: 'POP RAX; RET' },
 *   { id: '2', type: 'value', value: '0x3b', label: 'execve (59)' },
 * ];
 * const code = exportToPwntools(items, 40);
 * ```
 */
export const exportToPwntools = (stack: StackItem[], offset = 40): string => {
  const lines: string[] = [
    'from pwn import *',
    '',
    "context.arch = 'amd64'",
    "context.os = 'linux'",
    '',
    '# ROP Chain for binary exploitation',
    '# Generated by VStack - Visual ROP Chain Builder',
    '# Adjust ./binary and offset to your target (cyclic_find).',
    '',
    'elf = ELF("./binary")',
    'p = process("./binary")',
    '# p = remote("host", 1337)  # for remote CTF',
    '',
    `offset = ${offset}  # padding to RIP (buffer + saved RBP)`,
    'payload = b"A" * offset',
    '',
  ];

  for (const item of stack) {
    if (item.type === 'gadget' && item.gadgetId) {
      const gadget = getGadgetById(item.gadgetId);
      const comment = gadget ? gadget.instructions.join('; ') : (item.label || 'gadget');
      lines.push(`payload += flat(${item.value})  # ${comment}`);
    } else {
      lines.push(`payload += flat(${item.value})  # ${item.label || 'value'}`);
    }
  }

  lines.push('');
  lines.push('p.send(payload)');
  lines.push('p.interactive()  # you now have a shell if execve succeeded');

  return lines.join('\n');
};

/**
 * Copies text to the system clipboard using the Clipboard API.
 *
 * @param text - The text to copy to clipboard.
 * @returns `true` if the copy succeeded, `false` if it failed (e.g., no permission).
 *
 * @example
 * ```typescript
 * const success = await copyToClipboard('0x4005d3');
 * if (success) showCopiedFeedback();
 * ```
 */
export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
};
